/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author nicolebrito
 */
public class VistaNintendo extends javax.swing.JFrame {

    /**
     * Creates new form VistaNintendo
     */
    public VistaNintendo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        LogoNintendo = new javax.swing.JLabel();
        TituloCantidadesProducidas = new javax.swing.JLabel();
        TituloProductores = new javax.swing.JLabel();
        CantProductoresBotones = new javax.swing.JTextField();
        DisminuirProductoresBotones = new javax.swing.JButton();
        AumentarProductoresBotones = new javax.swing.JButton();
        TituloCantidadProductoresBotones = new javax.swing.JLabel();
        CantProductoresPantallas = new javax.swing.JTextField();
        DisminuirProductoresPantallas = new javax.swing.JButton();
        AumentarProductoresPantallas = new javax.swing.JButton();
        TituloCantidadProductoresPantallas = new javax.swing.JLabel();
        DisminuirProductoresJoystick = new javax.swing.JButton();
        CantProductoresJoystick = new javax.swing.JTextField();
        AumentarProductoresJoystick = new javax.swing.JButton();
        TituloCantidadProductoresJoystick = new javax.swing.JLabel();
        CantProductoresTarjetasSD = new javax.swing.JTextField();
        TituloCantidadProductoresTarjetasSD = new javax.swing.JLabel();
        AumentarProductoresTarjetasSD = new javax.swing.JButton();
        DisminuirProductoresTarjetasSD = new javax.swing.JButton();
        TituloEnsambladores = new javax.swing.JLabel();
        DisminuirEnsambladores = new javax.swing.JButton();
        CantEnsambladores = new javax.swing.JTextField();
        AumentarEnsambladores = new javax.swing.JButton();
        TituloCantidadBotones = new javax.swing.JLabel();
        CantidadBotones = new javax.swing.JTextField();
        TituloCantidadPantallasNormales = new javax.swing.JLabel();
        CantidadPantallasTactiles = new javax.swing.JTextField();
        TituloCantidadJoystick = new javax.swing.JLabel();
        CantidadJoystick = new javax.swing.JTextField();
        TituloCantidadTarjetasSD = new javax.swing.JLabel();
        CantidadConsolasDisponibles = new javax.swing.JTextField();
        CantidadPantallasNormales = new javax.swing.JTextField();
        TituloCantidadPantallasTactiles = new javax.swing.JLabel();
        CantidadTarjetasSD1 = new javax.swing.JTextField();
        TituloConsolasDisponibles = new javax.swing.JLabel();
        TituloDiasRestantes = new javax.swing.JLabel();
        EstadoGerente = new javax.swing.JTextField();
        TituloEstados = new javax.swing.JLabel();
        TituloJefe = new javax.swing.JLabel();
        TituloGerente = new javax.swing.JLabel();
        CantidadDias1 = new javax.swing.JTextField();
        EstadoJefe1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(692, 612));

        PanelBase.setBackground(new java.awt.Color(255, 204, 204));
        PanelBase.setPreferredSize(new java.awt.Dimension(616, 629));

        LogoNintendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nintendo_logo.png"))); // NOI18N

        TituloCantidadesProducidas.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        TituloCantidadesProducidas.setText("Cantidades manejadas por la empresa");

        TituloProductores.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        TituloProductores.setText("Número de Productores de la Compañía (puedes contratar o despedir)");

        CantProductoresBotones.setBackground(new java.awt.Color(255, 102, 102));
        CantProductoresBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantProductoresBotonesActionPerformed(evt);
            }
        });

        DisminuirProductoresBotones.setBackground(new java.awt.Color(204, 204, 204));
        DisminuirProductoresBotones.setText("-");
        DisminuirProductoresBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirProductoresBotonesActionPerformed(evt);
            }
        });

        AumentarProductoresBotones.setBackground(new java.awt.Color(204, 204, 204));
        AumentarProductoresBotones.setText("+");
        AumentarProductoresBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarProductoresBotonesActionPerformed(evt);
            }
        });

        TituloCantidadProductoresBotones.setText("Botones");

        CantProductoresPantallas.setBackground(new java.awt.Color(255, 102, 102));
        CantProductoresPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantProductoresPantallasActionPerformed(evt);
            }
        });

        DisminuirProductoresPantallas.setBackground(new java.awt.Color(204, 204, 204));
        DisminuirProductoresPantallas.setText("-");
        DisminuirProductoresPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirProductoresPantallasActionPerformed(evt);
            }
        });

        AumentarProductoresPantallas.setBackground(new java.awt.Color(204, 204, 204));
        AumentarProductoresPantallas.setText("+");
        AumentarProductoresPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarProductoresPantallasActionPerformed(evt);
            }
        });

        TituloCantidadProductoresPantallas.setText("Pantallas");

        DisminuirProductoresJoystick.setBackground(new java.awt.Color(204, 204, 204));
        DisminuirProductoresJoystick.setText("-");
        DisminuirProductoresJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirProductoresJoystickActionPerformed(evt);
            }
        });

        CantProductoresJoystick.setBackground(new java.awt.Color(255, 102, 102));
        CantProductoresJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantProductoresJoystickActionPerformed(evt);
            }
        });

        AumentarProductoresJoystick.setBackground(new java.awt.Color(204, 204, 204));
        AumentarProductoresJoystick.setText("+");
        AumentarProductoresJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarProductoresJoystickActionPerformed(evt);
            }
        });

        TituloCantidadProductoresJoystick.setText("Joystick");

        CantProductoresTarjetasSD.setBackground(new java.awt.Color(255, 102, 102));
        CantProductoresTarjetasSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantProductoresTarjetasSDActionPerformed(evt);
            }
        });

        TituloCantidadProductoresTarjetasSD.setText("Tarjetas SD");

        AumentarProductoresTarjetasSD.setBackground(new java.awt.Color(204, 204, 204));
        AumentarProductoresTarjetasSD.setText("+");
        AumentarProductoresTarjetasSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarProductoresTarjetasSDActionPerformed(evt);
            }
        });

        DisminuirProductoresTarjetasSD.setBackground(new java.awt.Color(204, 204, 204));
        DisminuirProductoresTarjetasSD.setText("-");
        DisminuirProductoresTarjetasSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirProductoresTarjetasSDActionPerformed(evt);
            }
        });

        TituloEnsambladores.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        TituloEnsambladores.setText("Ensambladores (puedes contratar o despedir)");

        DisminuirEnsambladores.setBackground(new java.awt.Color(204, 204, 204));
        DisminuirEnsambladores.setText("-");
        DisminuirEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirEnsambladoresActionPerformed(evt);
            }
        });

        CantEnsambladores.setBackground(new java.awt.Color(255, 102, 102));
        CantEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantEnsambladoresActionPerformed(evt);
            }
        });

        AumentarEnsambladores.setBackground(new java.awt.Color(204, 204, 204));
        AumentarEnsambladores.setText("+");
        AumentarEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarEnsambladoresActionPerformed(evt);
            }
        });

        TituloCantidadBotones.setText("Botones:");

        CantidadBotones.setBackground(new java.awt.Color(255, 102, 102));
        CantidadBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadBotonesActionPerformed(evt);
            }
        });

        TituloCantidadPantallasNormales.setText("Pantallas Normales:");

        CantidadPantallasTactiles.setBackground(new java.awt.Color(255, 102, 102));
        CantidadPantallasTactiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadPantallasTactilesActionPerformed(evt);
            }
        });

        TituloCantidadJoystick.setText("Joystick:");

        CantidadJoystick.setBackground(new java.awt.Color(255, 102, 102));
        CantidadJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadJoystickActionPerformed(evt);
            }
        });

        TituloCantidadTarjetasSD.setText("Tarjetas SD:");

        CantidadConsolasDisponibles.setBackground(new java.awt.Color(255, 102, 102));
        CantidadConsolasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadConsolasDisponiblesActionPerformed(evt);
            }
        });

        CantidadPantallasNormales.setBackground(new java.awt.Color(255, 102, 102));
        CantidadPantallasNormales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadPantallasNormalesActionPerformed(evt);
            }
        });

        TituloCantidadPantallasTactiles.setText("Pantallas Táctiles:");

        CantidadTarjetasSD1.setBackground(new java.awt.Color(255, 102, 102));
        CantidadTarjetasSD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadTarjetasSD1ActionPerformed(evt);
            }
        });

        TituloConsolasDisponibles.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        TituloConsolasDisponibles.setText("CONSOLAS DISPONIBLES:");

        TituloDiasRestantes.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        TituloDiasRestantes.setText("Días que faltan para el despliegue Global:");

        EstadoGerente.setBackground(new java.awt.Color(255, 102, 102));
        EstadoGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoGerenteActionPerformed(evt);
            }
        });

        TituloEstados.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        TituloEstados.setText("Estados");

        TituloJefe.setText("Jefe:");

        TituloGerente.setText("Gerente:");

        CantidadDias1.setBackground(new java.awt.Color(255, 102, 102));
        CantidadDias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadDias1ActionPerformed(evt);
            }
        });

        EstadoJefe1.setBackground(new java.awt.Color(255, 102, 102));
        EstadoJefe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoJefe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBaseLayout = new javax.swing.GroupLayout(PanelBase);
        PanelBase.setLayout(PanelBaseLayout);
        PanelBaseLayout.setHorizontalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                        .addComponent(LogoNintendo, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                .addComponent(DisminuirProductoresJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantProductoresJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AumentarProductoresJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                .addComponent(DisminuirProductoresBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantProductoresBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AumentarProductoresBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituloCantidadProductoresBotones, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TituloCantidadProductoresJoystick))
                                .addGap(68, 68, 68)))
                        .addGap(118, 118, 118)
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                        .addComponent(TituloCantidadProductoresPantallas)
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                        .addComponent(TituloCantidadProductoresTarjetasSD)
                                        .addGap(58, 58, 58))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                .addComponent(DisminuirProductoresTarjetasSD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantProductoresTarjetasSD, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AumentarProductoresTarjetasSD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                .addComponent(DisminuirProductoresPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantProductoresPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AumentarProductoresPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(165, 165, 165))))
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloProductores)
                            .addComponent(TituloCantidadesProducidas)
                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelBaseLayout.createSequentialGroup()
                                        .addComponent(TituloEnsambladores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DisminuirEnsambladores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                        .addGap(0, 14, Short.MAX_VALUE)
                                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CantidadTarjetasSD1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CantidadDias1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(PanelBaseLayout.createSequentialGroup()
                                                        .addComponent(TituloCantidadJoystick)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(CantidadJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(PanelBaseLayout.createSequentialGroup()
                                                        .addComponent(TituloCantidadBotones)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(CantidadBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PanelBaseLayout.createSequentialGroup()
                                                        .addGap(33, 33, 33)
                                                        .addComponent(TituloCantidadPantallasNormales)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(CantidadPantallasNormales, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBaseLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TituloCantidadTarjetasSD)
                                                        .addGap(107, 107, 107)))))
                                        .addGap(34, 34, 34)))
                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelBaseLayout.createSequentialGroup()
                                        .addComponent(CantEnsambladores, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AumentarEnsambladores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelBaseLayout.createSequentialGroup()
                                            .addComponent(TituloCantidadPantallasTactiles)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CantidadPantallasTactiles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBaseLayout.createSequentialGroup()
                                            .addComponent(TituloConsolasDisponibles)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CantidadConsolasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(23, 23, 23))
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloDiasRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                .addComponent(TituloEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TituloJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadoJefe1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(TituloGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(EstadoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelBaseLayout.setVerticalGroup(
            PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBaseLayout.createSequentialGroup()
                .addComponent(LogoNintendo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TituloProductores)
                .addGap(18, 18, 18)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addComponent(TituloCantidadProductoresPantallas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CantProductoresPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisminuirProductoresPantallas)
                            .addComponent(AumentarProductoresPantallas))
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloCantidadProductoresTarjetasSD)
                            .addGroup(PanelBaseLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CantProductoresTarjetasSD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisminuirProductoresTarjetasSD)
                                    .addComponent(AumentarProductoresTarjetasSD)))))
                    .addGroup(PanelBaseLayout.createSequentialGroup()
                        .addComponent(TituloCantidadProductoresBotones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CantProductoresBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisminuirProductoresBotones)
                            .addComponent(AumentarProductoresBotones))
                        .addComponent(TituloCantidadProductoresJoystick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CantProductoresJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisminuirProductoresJoystick)
                            .addComponent(AumentarProductoresJoystick))))
                .addGap(36, 36, 36)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisminuirEnsambladores)
                    .addComponent(CantEnsambladores, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AumentarEnsambladores)
                    .addComponent(TituloEnsambladores))
                .addGap(18, 18, 18)
                .addComponent(TituloCantidadesProducidas)
                .addGap(15, 15, 15)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloCantidadPantallasNormales)
                    .addComponent(CantidadPantallasNormales, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloCantidadBotones)
                    .addComponent(CantidadBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadPantallasTactiles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloCantidadPantallasTactiles))
                .addGap(16, 16, 16)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloCantidadJoystick)
                    .addComponent(TituloCantidadTarjetasSD)
                    .addComponent(CantidadConsolasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadTarjetasSD1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloConsolasDisponibles))
                .addGap(28, 28, 28)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloDiasRestantes)
                    .addComponent(CantidadDias1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloEstados)
                    .addComponent(TituloJefe)
                    .addComponent(EstadoJefe1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloGerente)
                    .addComponent(EstadoGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisminuirProductoresBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirProductoresBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisminuirProductoresBotonesActionPerformed

    private void CantProductoresBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantProductoresBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantProductoresBotonesActionPerformed

    private void AumentarProductoresBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarProductoresBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AumentarProductoresBotonesActionPerformed

    private void CantProductoresPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantProductoresPantallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantProductoresPantallasActionPerformed

    private void DisminuirProductoresPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirProductoresPantallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisminuirProductoresPantallasActionPerformed

    private void AumentarProductoresPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarProductoresPantallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AumentarProductoresPantallasActionPerformed

    private void DisminuirProductoresJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirProductoresJoystickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisminuirProductoresJoystickActionPerformed

    private void CantProductoresJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantProductoresJoystickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantProductoresJoystickActionPerformed

    private void AumentarProductoresJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarProductoresJoystickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AumentarProductoresJoystickActionPerformed

    private void CantProductoresTarjetasSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantProductoresTarjetasSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantProductoresTarjetasSDActionPerformed

    private void AumentarProductoresTarjetasSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarProductoresTarjetasSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AumentarProductoresTarjetasSDActionPerformed

    private void DisminuirProductoresTarjetasSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirProductoresTarjetasSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisminuirProductoresTarjetasSDActionPerformed

    private void DisminuirEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirEnsambladoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisminuirEnsambladoresActionPerformed

    private void CantEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantEnsambladoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantEnsambladoresActionPerformed

    private void AumentarEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarEnsambladoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AumentarEnsambladoresActionPerformed

    private void CantidadBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadBotonesActionPerformed

    private void CantidadPantallasTactilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadPantallasTactilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadPantallasTactilesActionPerformed

    private void CantidadJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadJoystickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadJoystickActionPerformed

    private void CantidadConsolasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadConsolasDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadConsolasDisponiblesActionPerformed

    private void CantidadPantallasNormalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadPantallasNormalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadPantallasNormalesActionPerformed

    private void CantidadTarjetasSD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadTarjetasSD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadTarjetasSD1ActionPerformed

    private void EstadoGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoGerenteActionPerformed

    private void CantidadDias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadDias1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadDias1ActionPerformed

    private void EstadoJefe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoJefe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoJefe1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNintendo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AumentarEnsambladores;
    private javax.swing.JButton AumentarProductoresBotones;
    private javax.swing.JButton AumentarProductoresJoystick;
    private javax.swing.JButton AumentarProductoresPantallas;
    private javax.swing.JButton AumentarProductoresTarjetasSD;
    private javax.swing.JTextField CantEnsambladores;
    private javax.swing.JTextField CantProductoresBotones;
    private javax.swing.JTextField CantProductoresJoystick;
    private javax.swing.JTextField CantProductoresPantallas;
    private javax.swing.JTextField CantProductoresTarjetasSD;
    private javax.swing.JTextField CantidadBotones;
    private javax.swing.JTextField CantidadConsolasDisponibles;
    private javax.swing.JTextField CantidadDias1;
    private javax.swing.JTextField CantidadJoystick;
    private javax.swing.JTextField CantidadPantallasNormales;
    private javax.swing.JTextField CantidadPantallasTactiles;
    private javax.swing.JTextField CantidadTarjetasSD1;
    private javax.swing.JButton DisminuirEnsambladores;
    private javax.swing.JButton DisminuirProductoresBotones;
    private javax.swing.JButton DisminuirProductoresJoystick;
    private javax.swing.JButton DisminuirProductoresPantallas;
    private javax.swing.JButton DisminuirProductoresTarjetasSD;
    private javax.swing.JTextField EstadoGerente;
    private javax.swing.JTextField EstadoJefe1;
    private javax.swing.JLabel LogoNintendo;
    private javax.swing.JPanel PanelBase;
    private javax.swing.JLabel TituloCantidadBotones;
    private javax.swing.JLabel TituloCantidadJoystick;
    private javax.swing.JLabel TituloCantidadPantallasNormales;
    private javax.swing.JLabel TituloCantidadPantallasTactiles;
    private javax.swing.JLabel TituloCantidadProductoresBotones;
    private javax.swing.JLabel TituloCantidadProductoresJoystick;
    private javax.swing.JLabel TituloCantidadProductoresPantallas;
    private javax.swing.JLabel TituloCantidadProductoresTarjetasSD;
    private javax.swing.JLabel TituloCantidadTarjetasSD;
    private javax.swing.JLabel TituloCantidadesProducidas;
    private javax.swing.JLabel TituloConsolasDisponibles;
    private javax.swing.JLabel TituloDiasRestantes;
    private javax.swing.JLabel TituloEnsambladores;
    private javax.swing.JLabel TituloEstados;
    private javax.swing.JLabel TituloGerente;
    private javax.swing.JLabel TituloJefe;
    private javax.swing.JLabel TituloProductores;
    // End of variables declaration//GEN-END:variables
}
